const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
const GET_BY_ID = "GET_BY_ID";
const SORT_CONFIG = "SORT_CONFIG";
const RESET_CONFIG = "RESET_CONFIG";

export {
    GET_ALL_COUNTRIES,
    GET_BY_ID,
    SORT_CONFIG,
    RESET_CONFIG,
};